#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
# console_title_template = "{{ .Shell }} in {{ .Folder }}"
console_title_template = "{{ .Folder }}"
enable_cursor_positioning = true

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    template = "➜ "
  
  # [[blocks.segments]]
  #   leading_diamond = ""
  #   style = "plain"
  #   template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}}"
  #   trailing_diamond = "<transparent,#FEF5ED></>"
  #   type = "os"

  #   [blocks.segments.properties]
  #     macos = " "
  #     ubuntu = " "
  #     windows = " "

  # [[blocks.segments]]
  # type = "session"
  # style = "plain"
  # template = " {{ .UserName }} on "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    background = "transparent"
    foreground = "p:cyan-alt"
    # template = "{{ .Path }}"
    # template = " 󰉖 {{ path .Path .Location }}"
    template = "󰉖 {{ path .Path .Location }}"
   
    [blocks.segments.properties]
      folder_separator_icon = "/"
      style = "full"
 
  
  [[blocks.segments]]
    type = "git"
    style = "plain"
    background = "transparent"
    foreground = "p:git-grey"
    template = " <#a0a0a0>{{.Working.Untracked}}</> {{ url .HEAD .UpstreamURL }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}↓{{ .Behind}}{{ end }}{{ if gt .Ahead 0}}↑{{ .Ahead}}{{end}}</>"
    # template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}"
   
   
    [blocks.segments.properties]
      commit_icon  = "@"
      fetch_status = true

[[blocks]]
  type = "prompt"
  alignment = "right"
  # overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:yellow"
    background = "transparent"
    template = " {{ div .Ms 1000 }}s "

     [blocks.segments.properties]
      threshold = 5000 
  
  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "#3670A0"
    background = "transparent"
    template = " {{ if .Venv }}{{ .Venv }}{{ end }} "
    # template = " {{ if .Venv }}{{ .Venv }} {{ .Full }} {{ end }}"
      [blocks.segments.properties]
        cache_version = true
        display_mode = "files"

  [[blocks.segments]]
    type = "php"
    style = "plain"
    foreground = "#777bb4"
    template = " "
    
  [[blocks.segments]]  
    type = "node"
    style = "plain"
    foreground = "#6CA35E"
    template = " "


   [[blocks.segments]]
    type = "command"
    style = "plain"
    foreground = "p:git-grey"
    template = "| {{ .Output }}"

    [blocks.segments.properties]
      command = "git log --pretty=format:%cr -1"
      shell = "bash"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:white"
    background = "transparent"
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
    ]
    template = "▷"

[transient_prompt]
  foreground = "p:white"
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
  ]
  background = 'transparent'
  template = '▷ '

[secondary_prompt]
  foreground = "#999999"
  background = "transparent"
  template = "❭❭ "


[palette]
  cyan-alt = "#3cdfff"
  git-grey ="#6c6c6c"
  black = "#262B44"
  paleblue = "#4B95E9"
  # lightblue = "#8aecff"
  lightblue = "#63e5ff"
  cyan = "#00FFFF"
  pistach-green = "#9ece6a"
  green = "#59C9A5"
  orange = "#F07623"
  red = "#D81E5B"
  magenta = "#FF0080"
  white = "#f0f0f0"
  yellow = "#F3AE35"